import { NextResponse, type NextRequest } from 'next/server'
import { getSession } from '@/lib/auth'
import pool, { ready } from '@/lib/db'
import { sendPlusVibeReply, getPlusVibeInbound } from '@/lib/plusvibe'
import { notifyAdmin } from '@/lib/notify'
import { getLockedLeadIds } from '@/lib/balance'

// POST — client replies to a lead.
// 1. Persist the outgoing message to portal_emails (so it shows in the thread immediately)
// 2. Attempt live send via PlusVibe
// 3. Always notify the team (so a reply is never lost, even if live-send isn't wired)
export async function POST(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const session = await getSession()
  if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  await ready() // ensure portal_attachments exists before storing files
  const { id } = await params

  let body: string, bodyHtml: string | undefined, cc: string | undefined, to: string | undefined
  const attachments: { filename: string; contentType: string; content: Buffer }[] = []

  const contentType = req.headers.get('content-type') ?? ''
  if (contentType.includes('multipart/form-data')) {
    const fd = await req.formData()
    body = (fd.get('body') as string | null) ?? ''
    bodyHtml = (fd.get('bodyHtml') as string | null) ?? undefined
    to = (fd.get('to') as string | null) ?? undefined
    cc = (fd.get('cc') as string | null) ?? undefined
    // Explicit filename list (parallel to the file parts) — the multipart filename
    // can be dropped/regenerated by the parser, so prefer this when present.
    const fileNames = fd.getAll('fileNames').map(v => String(v))
    const fileParts = fd.getAll('files').filter((v): v is File => v instanceof Blob)
    for (let idx = 0; idx < fileParts.length; idx++) {
      const blob = fileParts[idx]
      // Prefer the explicit name; fall back to the part's own name; never a UUID.
      const name = fileNames[idx] || blob.name || `attachment-${idx + 1}`
      attachments.push({
        filename: name,
        contentType: blob.type || 'application/octet-stream',
        content: Buffer.from(await blob.arrayBuffer()),
      })
    }
  } else {
    const j = await req.json() as { body: string; bodyHtml?: string; cc?: string; to?: string }
    body = j.body; bodyHtml = j.bodyHtml; cc = j.cc; to = j.to
  }

  if (!body?.trim()) return NextResponse.json({ error: 'Empty reply' }, { status: 400 })
  const html = bodyHtml?.trim() ? bodyHtml : `<p>${body.replace(/\n/g, '<br/>')}</p>`

  // Recipients can be separated by comma, space or semicolon.
  const parseAddrs = (s?: string) => (s ?? '').split(/[\s,;]+/).map(x => x.trim()).filter(x => x.includes('@'))

  const leadRes = await pool.query(
    'SELECT id, email, first_name, last_name FROM esp_leads WHERE id = $1 AND workspace_id = $2',
    [id, session.workspaceId]
  )
  if (!leadRes.rows.length) return NextResponse.json({ error: 'Not found' }, { status: 404 })
  const lead = leadRes.rows[0]

  // Can't reply to a locked lead (delivered while out of credit) — top up first.
  const lockedIds = await getLockedLeadIds(session.clientId)
  if (lockedIds.has(id)) return NextResponse.json({ error: 'This lead is locked. Top up to unlock it before replying.' }, { status: 403 })

  // Recipients — default to the lead; client can send/forward to multiple addresses.
  const toAddrs = parseAddrs(to)
  const toList = (toAddrs.length ? toAddrs : [lead.email]).join(', ')
  const ccList = parseAddrs(cc).join(', ')
  const toAddr = toAddrs[0] || lead.email

  // Find the latest inbound message for threading context.
  // Prefer a PlusVibe ID (unibox_ or pv_) when one exists so the reply threads in PV.
  const ctx = await pool.query(
    `SELECT id, subject, eaccount, to_email, message_id FROM portal_emails
      WHERE workspace_id = $1 AND lower(lead_email) = lower($2) AND direction = 'IN'
      ORDER BY (id LIKE 'unibox_%' OR id LIKE 'pv_%') DESC, timestamp_created DESC LIMIT 1`,
    [session.workspaceId, lead.email]
  )
  const subject = ctx.rows[0]?.subject ?? 'Re: your enquiry'
  // Sending mailbox (the reply FROM). portal_emails.eaccount can be NULL for
  // PV-ingested rows, which made PlusVibe reject the reply with
  // pv_400 "from is required". Fall back to unibox_replies.mailbox_email — the
  // mailbox that RECEIVED the lead's reply (set by both ingest paths from
  // primary_to_email_address), i.e. exactly the address we should reply from.
  let eaccount = ctx.rows[0]?.eaccount ?? ctx.rows[0]?.to_email ?? undefined
  if (!eaccount) {
    const mb = await pool.query(
      `SELECT mailbox_email, sender_email FROM unibox_replies
        WHERE workspace_id = $1 AND lower(lead_email) = lower($2)
          AND mailbox_email IS NOT NULL AND mailbox_email <> ''
        ORDER BY received_at DESC LIMIT 1`,
      [session.workspaceId, lead.email]
    ).catch(() => ({ rows: [] as { mailbox_email?: string; sender_email?: string }[] }))
    eaccount = mb.rows[0]?.mailbox_email || undefined
  }
  const inboundId: string | null = ctx.rows[0]?.id ?? null

  // 1. Persist outgoing message (synthetic id so it's stable + idempotent-ish).
  const outId = `portal-${id}-${Date.now()}`

  // Store each attachment's bytes so it can be previewed/downloaded later, and
  // collect its metadata (id/filename/size/type) for the email's raw so the
  // thread can render clickable chips.
  const attachMeta: { id: string; filename: string; size: number; content_type: string }[] = []
  for (const a of attachments) {
    try {
      const ins = await pool.query(
        `INSERT INTO portal_attachments (email_id, workspace_id, filename, content_type, size, content)
         VALUES ($1,$2,$3,$4,$5,$6) RETURNING id`,
        [outId, session.workspaceId, a.filename, a.contentType, a.content.length, a.content.toString('base64')]
      )
      attachMeta.push({ id: ins.rows[0].id as string, filename: a.filename, size: a.content.length, content_type: a.contentType })
    } catch (err) {
      // An attachment that fails to persist must NOT silently send without it —
      // the client thinks the file went; the lead never gets it. Abort with a
      // clear error so the client retries, instead of a half-sent reply.
      console.error('[reply] attachment persist failed:', err)
      return NextResponse.json({ error: 'Could not attach your file — please try again.' }, { status: 500 })
    }
  }
  const rawMeta = attachMeta.length ? JSON.stringify({ attachments: attachMeta }) : '{}'

  // Sending identity is ONLY ever the resolved client mailbox. NEVER fall back to
  // session.email (the client's LOGIN address) — that would put a wrong/Ottaly
  // identity on the thread row. If unresolved, store null; the live send below
  // will fail cleanly and the team is notified to send manually.
  await pool.query(
    `INSERT INTO portal_emails (
       id, workspace_id, lead_email, direction, subject, body_text, body_html,
       content_preview, from_email, to_email, eaccount, sent_via_portal, timestamp_created, raw
     ) VALUES ($1,$2,$3,'OUT',$4,$5,$6,$7,$8,$9,$10,TRUE,NOW(),$11::jsonb)`,
    [
      outId, session.workspaceId, lead.email.toLowerCase(), subject, body,
      html, body.slice(0, 200),
      eaccount ?? null, toList, eaccount ?? null, rawMeta,
    ]
  ).catch(err => console.error('[reply] persist failed:', err))

  // 2. Attempt live send.
  // PlusVibe is the ONLY send path for a client reply — always from the CLIENT'S
  // mailbox. Resend is NEVER used to send mail to a lead (it leaked Ottaly's
  // identity); it's strictly notifications now. Bison/EmailBison is retired, and we
  // do NOT branch on the inbound id prefix. Attachments are sent natively by PV
  // (file_name + base64), so a reply with a file still goes from the client.
  let send: { ok: boolean; reason?: string } = { ok: false, reason: 'no-reply-id-in-cache' }
  {
    // Resolve the REAL PlusVibe email id + sending mailbox from the unibox API by
    // lead email. Our DB id may be synthetic (unibox_/pv_) or a stale numeric
    // Bison id — neither is what PV's reply API wants, so we always look up the
    // live PV id by the lead's address.
    const pv = await getPlusVibeInbound(session.workspaceId, lead.email)
    const fromMailbox = pv?.from || eaccount
    // Strip any known prefix; if it's a plain-numeric Bison id we can't use it as
    // a PV reply_to_id, so prefer the freshly-resolved PV id.
    const strippedId = (inboundId ?? '').replace(/^(unibox_|pv_)/, '')
    const replyToId = pv?.id || (/^[a-f0-9]{8,}$/i.test(strippedId) ? strippedId : '')
    if (!fromMailbox || !replyToId) {
      // Couldn't resolve a PV thread to reply to (no live PV email for this lead,
      // or no sending mailbox). Surface a clear reason so it's flagged for manual
      // send instead of a cryptic error or a dead-Bison attempt.
      send = { ok: false, reason: !replyToId ? 'no-plusvibe-thread-resolved' : 'no-sending-mailbox-resolved' }
    } else {
      send = await sendPlusVibeReply({
        workspaceId: session.workspaceId,
        replyToId,
        subject: subject,
        from: fromMailbox,
        to: toList,
        body: html,
        cc: ccList || undefined,
        attachments: attachments.length ? attachments : undefined,
      })
    }
  }

  // Stamp sent_live so the retry endpoint can skip already-sent replies.
  await pool.query(
    `UPDATE portal_emails SET sent_live = $1 WHERE id = $2`,
    [send.ok, outId]
  ).catch(() => {})

  // 3. Notify team (always — guarantees the reply is actioned)
  // Stamp the client's first response time (for Speed to Lead) — once per lead.
  await pool.query(
    `INSERT INTO portal_lead_data (lead_id, client_id, first_responded_at)
     VALUES ($1, $2, NOW())
     ON CONFLICT (lead_id, client_id) DO UPDATE
       SET first_responded_at = COALESCE(portal_lead_data.first_responded_at, NOW())`,
    [id, session.clientId]
  ).catch(() => {})

  const who = [lead.first_name, lead.last_name].filter(Boolean).join(' ') || lead.email
  // The client always sees "sent". If live-send didn't go through, the team MUST
  // send it manually — make that scannable in the title, and ALWAYS include the
  // To + Cc so the manual send replicates exactly who the client addressed.
  await notifyAdmin({
    clientId: session.clientId,
    kind: 'reply_sent',
    title: send.ok
      ? `${session.companyName} replied re: ${who}`
      : `⚠️ SEND MANUALLY — ${session.companyName} re: ${who}`,
    body: `${send.ok ? '✅ Sent live via PlusVibe' : '⚠️ NOT auto-sent (' + send.reason + ') — PLEASE SEND THIS MANUALLY'}\nFrom (client mailbox): ${eaccount ?? '— unresolved —'}\nTo: ${toList}\nCc: ${ccList || '(none)'}\nSubject: ${subject}\n\n${body}`,
  })

  return NextResponse.json({ ok: true, sentLive: send.ok })
}
