import { NextResponse, type NextRequest } from 'next/server'
import { getSession } from '@/lib/auth'
import pool, { ready } from '@/lib/db'
import { sendPlusVibeReply, getPlusVibeInbound } from '@/lib/plusvibe'
import { notifyAdmin } from '@/lib/notify'
import { getLockedLeadIds } from '@/lib/balance'

// POST — client replies to a lead.
// 1. Persist the outgoing message to portal_emails (so it shows in the thread immediately)
// 2. Attempt live send via PlusVibe
// 3. Always notify the team (so a reply is never lost, even if live-send isn't wired)
export async function POST(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const session = await getSession()
  if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  await ready() // ensure portal_attachments exists before storing files
  const { id } = await params

  let body: string, bodyHtml: string | undefined, cc: string | undefined, to: string | undefined
  const attachments: { filename: string; contentType: string; content: Buffer }[] = []

  const contentType = req.headers.get('content-type') ?? ''
  if (contentType.includes('multipart/form-data')) {
    const fd = await req.formData()
    body = (fd.get('body') as string | null) ?? ''
    bodyHtml = (fd.get('bodyHtml') as string | null) ?? undefined
    to = (fd.get('to') as string | null) ?? undefined
    cc = (fd.get('cc') as string | null) ?? undefined
    // Explicit filename list (parallel to the file parts) — the multipart filename
    // can be dropped/regenerated by the parser, so prefer this when present.
    const fileNames = fd.getAll('fileNames').map(v => String(v))
    const fileParts = fd.getAll('files').filter((v): v is File => v instanceof Blob)
    for (let idx = 0; idx < fileParts.length; idx++) {
      const blob = fileParts[idx]
      // Prefer the explicit name; fall back to the part's own name; never a UUID.
      const name = fileNames[idx] || blob.name || `attachment-${idx + 1}`
      attachments.push({
        filename: name,
        contentType: blob.type || 'application/octet-stream',
        content: Buffer.from(await blob.arrayBuffer()),
      })
    }
  } else {
    const j = await req.json() as { body: string; bodyHtml?: string; cc?: string; to?: string }
    body = j.body; bodyHtml = j.bodyHtml; cc = j.cc; to = j.to
  }

  if (!body?.trim()) return NextResponse.json({ error: 'Empty reply' }, { status: 400 })
  const html = bodyHtml?.trim() ? bodyHtml : `<p>${body.replace(/\n/g, '<br/>')}</p>`

  // Recipients can be separated by comma, space or semicolon.
  const parseAddrs = (s?: string) => (s ?? '').split(/[\s,;]+/).map(x => x.trim()).filter(x => x.includes('@'))

  const leadRes = await pool.query(
    'SELECT id, email, first_name, last_name FROM esp_leads WHERE id = $1 AND workspace_id = $2',
    [id, session.workspaceId]
  )
  if (!leadRes.rows.length) return NextResponse.json({ error: 'Not found' }, { status: 404 })
  const lead = leadRes.rows[0]

  // Can't reply to a locked lead (delivered while out of credit) — top up first.
  const lockedIds = await getLockedLeadIds(session.clientId)
  if (lockedIds.has(id)) return NextResponse.json({ error: 'This lead is locked. Top up to unlock it before replying.' }, { status: 403 })

  // Recipients — default to the lead; client can send/forward to multiple addresses.
  const toAddrs = parseAddrs(to)
  const toList = (toAddrs.length ? toAddrs : [lead.email]).join(', ')
  const ccList = parseAddrs(cc).join(', ')
  const toAddr = toAddrs[0] || lead.email

  // Find the latest inbound message for threading context.
  // Prefer a PlusVibe ID (unibox_ or pv_) when one exists so the reply threads in PV.
  const ctx = await pool.query(
    `SELECT id, subject, eaccount, to_email, message_id FROM portal_emails
      WHERE workspace_id = $1 AND lower(lead_email) = lower($2) AND direction = 'IN'
      ORDER BY (id LIKE 'unibox_%' OR id LIKE 'pv_%') DESC, timestamp_created DESC LIMIT 1`,
    [session.workspaceId, lead.email]
  )
  const subject = ctx.rows[0]?.subject ?? 'Re: your enquiry'
  // Sending mailbox (the reply FROM). portal_emails.eaccount can be NULL for
  // PV-ingested rows, which made PlusVibe reject the reply with
  // pv_400 "from is required". Fall back to unibox_replies.mailbox_email — the
  // mailbox that RECEIVED the lead's reply (set by both ingest paths from
  // primary_to_email_address), i.e. exactly the address we should reply from.
  let eaccount = ctx.rows[0]?.eaccount ?? ctx.rows[0]?.to_email ?? undefined
  if (!eaccount) {
    const mb = await pool.query(
      `SELECT mailbox_email, sender_email FROM unibox_replies
        WHERE workspace_id = $1 AND lower(lead_email) = lower($2)
          AND mailbox_email IS NOT NULL AND mailbox_email <> ''
        ORDER BY received_at DESC LIMIT 1`,
      [session.workspaceId, lead.email]
    ).catch(() => ({ rows: [] as { mailbox_email?: string; sender_email?: string }[] }))
    eaccount = mb.rows[0]?.mailbox_email || undefined
  }
  const inboundId: string | null = ctx.rows[0]?.id ?? null

  // 1. Persist outgoing message (synthetic id so it's stable + idempotent-ish).
  const outId = `portal-${id}-${Date.now()}`

  // Store each attachment's bytes so it can be previewed/downloaded later, and
  // collect its metadata (id/filename/size/type) for the email's raw so the
  // thread can render clickable chips.
  const attachMeta: { id: string; filename: string; size: number; content_type: string }[] = []
  for (const a of attachments) {
    try {
      const ins = await pool.query(
        `INSERT INTO portal_attachments (email_id, workspace_id, filename, content_type, size, content)
         VALUES ($1,$2,$3,$4,$5,$6) RETURNING id`,
        [outId, session.workspaceId, a.filename, a.contentType, a.content.length, a.content.toString('base64')]
      )
      attachMeta.push({ id: ins.rows[0].id as string, filename: a.filename, size: a.content.length, content_type: a.contentType })
    } catch (err) {
      // An attachment that fails to persist must NOT silently send without it —
      // the client thinks the file went; the lead never gets it. Abort with a
      // clear error so the client retries, instead of a half-sent reply.
      console.error('[reply] attachment persist failed:', err)
      return NextResponse.json({ error: 'Could not attach your file — please try again.' }, { status: 500 })
    }
  }
  // Persist into raw: attachment metadata AND the Cc list, so the client thread
  // can SHOW who was cc'd (it's otherwise only in the live-send + admin notify).
  const rawObj: Record<string, unknown> = {}
  if (attachMeta.length) rawObj.attachments = attachMeta
  if (ccList) rawObj.cc = ccList
  const rawMeta = JSON.stringify(rawObj)

  // Reply signature: if this client has it enabled, append their signature. We build
  // TWO versions: one for the live SEND (keeps the {{sender_signature}} token so
  // PlusVibe expands it to the mailbox's real signature) and one for the STORED thread
  // copy (any {{...}} tokens stripped, so the client SEES their custom signature in the
  // thread but never a raw token). A literal/custom signature shows in both.
  let outboundHtml = html
  let storedHtml = html
  let storedBody = body
  try {
    const sig = await pool.query(
      `SELECT reply_signature_enabled, reply_signature FROM portal_clients WHERE id = $1`,
      [session.clientId]
    )
    const row = sig.rows[0]
    const sigText = (row?.reply_signature ?? '').toString().trim()
    if (row?.reply_signature_enabled && sigText) {
      const isHtml = /<[a-z][\s\S]*>/i.test(sigText)
      // SEND copy keeps the token; convert newlines only for plain-text signatures.
      const sigHtmlSend = isHtml || sigText.includes('{{') ? sigText : sigText.replace(/\n/g, '<br/>')
      outboundHtml = `${html}<br/><br/>${sigHtmlSend}`
      // STORED/DISPLAY copy drops {{...}} tokens (we can't render what PV will inject).
      const sigSansTokens = sigText.replace(/\{\{[^}]*\}\}/g, '').trim()
      if (sigSansTokens) {
        storedHtml = `${html}<br/><br/>${isHtml ? sigSansTokens : sigSansTokens.replace(/\n/g, '<br/>')}`
        storedBody = `${body}\n\n${sigSansTokens}`
      }
    }
  } catch (err) {
    console.error('[reply] signature lookup failed:', err)
  }

  // Sending identity is ONLY ever the resolved client mailbox. NEVER fall back to
  // session.email (the client's LOGIN address) — that would put a wrong/Ottaly
  // identity on the thread row. If unresolved, store null; the live send below
  // will fail cleanly and the team is notified to send manually.
  await pool.query(
    `INSERT INTO portal_emails (
       id, workspace_id, lead_email, direction, subject, body_text, body_html,
       content_preview, from_email, to_email, eaccount, sent_via_portal, timestamp_created, raw
     ) VALUES ($1,$2,$3,'OUT',$4,$5,$6,$7,$8,$9,$10,TRUE,NOW(),$11::jsonb)`,
    [
      outId, session.workspaceId, lead.email.toLowerCase(), subject, storedBody,
      storedHtml, storedBody.slice(0, 200),
      eaccount ?? null, toList, eaccount ?? null, rawMeta,
    ]
  ).catch(err => console.error('[reply] persist failed:', err))

  // 2. Attempt live send.
  // PlusVibe is the ONLY send path for a client reply — always from the CLIENT'S
  // mailbox. Resend is NEVER used to send mail to a lead (it leaked Ottaly's
  // identity); it's strictly notifications now. Bison/EmailBison is retired, and we
  // do NOT branch on the inbound id prefix. Attachments are sent natively by PV
  // (file_name + base64), so a reply with a file still goes from the client.

  let send: { ok: boolean; reason?: string } = { ok: false, reason: 'no-reply-id-in-cache' }
  {
    // Resolve the REAL PlusVibe email id + sending mailbox from the unibox API by
    // lead email. Our DB id may be synthetic (unibox_/pv_) or a stale numeric
    // Bison id — neither is what PV's reply API wants, so we always look up the
    // live PV id by the lead's address.
    // Also pass any ALTERNATE addresses the lead replied from (a colleague's
    // mailbox), recorded at ingest, so a colleague-address reply still resolves
    // instead of flipping to "send manually".
    // Collect EVERY address this lead's thread may have replied FROM: the recorded
    // sender_email AND matched_lead_email. PV often threads a colleague at the same
    // company (e.g. lead=tom@acme, but jess@acme actually replied) — PV's inbound
    // email then has from_address_email=jess@, which getPlusVibeInbound rejects
    // unless jess@ is in acceptFrom. That colleague address lives in
    // matched_lead_email, so pulling ONLY sender_email missed it and flipped a
    // genuine reply to "SEND MANUALLY" (no-plusvibe-thread-resolved).
    const alt = await pool.query(
      `SELECT DISTINCT addr FROM (
         SELECT sender_email       AS addr FROM unibox_replies
           WHERE workspace_id = $1
             AND (lower(lead_email) = lower($2) OR lower(matched_lead_email) = lower($2))
         UNION
         SELECT matched_lead_email AS addr FROM unibox_replies
           WHERE workspace_id = $1
             AND (lower(lead_email) = lower($2) OR lower(matched_lead_email) = lower($2))
       ) a
       WHERE addr IS NOT NULL AND addr <> '' AND lower(addr) <> lower($2)`,
      [session.workspaceId, lead.email]
    ).catch(() => ({ rows: [] as { addr?: string }[] }))
    const acceptFrom = alt.rows.map(r => r.addr!).filter(Boolean)

    // The RFC Message-ID of the exact reply we're answering, captured at ingest as
    // unibox_replies.bison_reply_id = `pv_<message-id>`. This is what PV's own reply
    // UI targets a thread by, so we hand it to the resolver for an EXACT match —
    // robust even when PV's loose `lead=` filter returns another lead's email first.
    // THE PV EMAIL ID WE ALREADY HAVE. At ingest we store PlusVibe's own email
    // object verbatim (`raw = JSON.stringify(e)`), so `raw->>'id'` IS the exact
    // field the live resolver would go looking for — the one PV wants as
    // `reply_to_id`. We were throwing it away and re-searching PV for it, via a
    // `lead=` filter that PV IGNORES (verified live), which is what produced
    // "SEND MANUALLY" ~17% of the time. Read it straight from the DB instead:
    // it's exact, free, and can't be paged out of a feed.
    //
    // `bison_reply_id` holds a bare PV id on some rows too (older ingest path),
    // so accept that shape as well — the previous `LIKE 'pv_%'` filter discarded
    // precisely the rows that carried a usable id.
    const stored = await pool.query(
      `SELECT COALESCE(
                NULLIF(raw->>'id',''),
                CASE WHEN bison_reply_id ~ '^[a-f0-9]{16,}$' THEN bison_reply_id END
              ) AS pv_id,
              NULLIF(raw->>'eaccount','') AS pv_eaccount,
              NULLIF(raw->>'message_id','') AS pv_msg_id
         FROM unibox_replies
        WHERE workspace_id = $1
          AND (lower(lead_email) = lower($2) OR lower(matched_lead_email) = lower($2))
        ORDER BY received_at DESC`,
      [session.workspaceId, lead.email]
    ).catch(() => ({ rows: [] as { pv_id?: string; pv_eaccount?: string; pv_msg_id?: string }[] }))
    // Newest row that actually carries a PV-shaped id.
    const storedRow = stored.rows.find(r => /^[a-f0-9]{16,}$/i.test(r.pv_id ?? ''))
    const wantMsgId = (stored.rows.find(r => r.pv_msg_id)?.pv_msg_id) ?? null

    // Only hit the API when we DON'T already know the id — that's the slow,
    // lossy path, now a fallback rather than the default.
    const pv = storedRow ? null : await getPlusVibeInbound(session.workspaceId, lead.email, acceptFrom, wantMsgId)

    // Strip any known prefix; if it's a plain-numeric Bison id we can't use it as
    // a PV reply_to_id, so prefer a real PV id.
    const strippedId = (inboundId ?? '').replace(/^(unibox_|pv_)/, '')
    const replyToId = storedRow?.pv_id || pv?.id || (/^[a-f0-9]{16,}$/i.test(strippedId) ? strippedId : '')
    const fromMailbox = storedRow?.pv_eaccount || pv?.from || eaccount
    if (!fromMailbox || !replyToId) {
      // Couldn't resolve a PV thread to reply to (no live PV email for this lead,
      // or no sending mailbox). Surface a clear reason so it's flagged for manual
      // send instead of a cryptic error or a dead-Bison attempt.
      send = { ok: false, reason: !replyToId ? 'no-plusvibe-thread-resolved' : 'no-sending-mailbox-resolved' }
    } else {
      send = await sendPlusVibeReply({
        workspaceId: session.workspaceId,
        replyToId,
        subject: subject,
        from: fromMailbox,
        to: toList,
        body: outboundHtml,
        cc: ccList || undefined,
        attachments: attachments.length ? attachments : undefined,
      })
      // A stored id can go stale (thread archived/purged in PV) — PV then rejects
      // it with a permanent 4xx. Don't fall to manual while we still have the live
      // resolver untried: re-resolve against the API and send once more.
      if (!send.ok && storedRow && !/^pv_(429|5\d\d)/.test(send.reason ?? '')) {
        const live = await getPlusVibeInbound(session.workspaceId, lead.email, acceptFrom, wantMsgId)
        if (live?.id && live.id !== replyToId) {
          send = await sendPlusVibeReply({
            workspaceId: session.workspaceId,
            replyToId: live.id,
            subject: subject,
            from: live.from || fromMailbox,
            to: toList,
            body: outboundHtml,
            cc: ccList || undefined,
            attachments: attachments.length ? attachments : undefined,
          })
        }
      }
    }
  }

  // Stamp sent_live so the retry endpoint can skip already-sent replies.
  await pool.query(
    `UPDATE portal_emails SET sent_live = $1 WHERE id = $2`,
    [send.ok, outId]
  ).catch(() => {})

  // 3. Notify team (always — guarantees the reply is actioned)
  // Stamp the client's first response time (for Speed to Lead) — once per lead.
  await pool.query(
    `INSERT INTO portal_lead_data (lead_id, client_id, first_responded_at)
     VALUES ($1, $2, NOW())
     ON CONFLICT (lead_id, client_id) DO UPDATE
       SET first_responded_at = COALESCE(portal_lead_data.first_responded_at, NOW())`,
    [id, session.clientId]
  ).catch(() => {})

  const who = [lead.first_name, lead.last_name].filter(Boolean).join(' ') || lead.email
  // The client always sees "sent". If live-send didn't go through, the team MUST
  // send it manually — make that scannable in the title, and ALWAYS include the
  // To + Cc so the manual send replicates exactly who the client addressed.
  // MUST be best-effort: the reply may already be sent live via PlusVibe by this
  // point, so a notify failure must never bubble up and 500 the request —
  // otherwise the client sees "Could not send" for a reply that DID send. The
  // notification is a backstop; losing it is acceptable, a false failure is not.
  try {
    await notifyAdmin({
      clientId: session.clientId,
      kind: 'reply_sent',
      title: send.ok
        ? `${session.companyName} replied re: ${who}`
        : `⚠️ SEND MANUALLY — ${session.companyName} re: ${who}`,
      body: `${send.ok ? '✅ Sent live via PlusVibe' : '⚠️ NOT auto-sent (' + send.reason + ') — PLEASE SEND THIS MANUALLY'}\nFrom (client mailbox): ${eaccount ?? '— unresolved —'}\nTo: ${toList}\nCc: ${ccList || '(none)'}\nSubject: ${subject}\n\n${body}`,
    })
  } catch (err) {
    console.error('[reply] notifyAdmin failed (reply already handled — not failing the request):', err)
  }

  return NextResponse.json({ ok: true, sentLive: send.ok })
}
